"""
Layer 2: 集成测试
==================
验证组件之间的协作：
  - WorktreePool + RalphLoop 协作
  - WebServer API 响应
  - 完整的 submit → dispatch → merge 流程
"""

import asyncio
import json
import os
import pytest
import subprocess
import sys
from pathlib import Path
from unittest.mock import AsyncMock, patch

sys.path.insert(0, str(Path(__file__).parent.parent))
from manager import (
    CCDispatcher, WorktreePool, RalphLoop, WebServer,
    Task, TaskStatus
)


# ============================================================
# 辅助: Mock Dispatcher（完成时在 worktree 里创建文件）
# ============================================================

class FileCreatingDispatcher:
    """模拟 CC Dispatcher：在 worktree 中创建文件并 commit。"""

    def __init__(self, delay=0.01):
        self.delay = delay
        self.system_prompt = ""

    async def run(self, task, workdir=None, on_event=None):
        await asyncio.sleep(self.delay)
        task.started_at = "2026-01-01T00:00:00"

        try:
            # 模拟 CC agent 的工作：创建文件
            filename = f"output_{task.id}.py"
            filepath = Path(workdir) / filename
            filepath.write_text(f"# Generated by task {task.id}\nresult = 'OK'\n")

            # Git add + commit
            subprocess.run(["git", "add", "."], cwd=workdir,
                           capture_output=True, check=True)
            subprocess.run(
                ["git", "commit", "-m", f"feat: complete task {task.id}"],
                cwd=workdir, capture_output=True, check=True,
                env={**os.environ,
                     "GIT_AUTHOR_NAME": "agent", "GIT_AUTHOR_EMAIL": "a@t.com",
                     "GIT_COMMITTER_NAME": "agent", "GIT_COMMITTER_EMAIL": "a@t.com"}
            )

            task.status = TaskStatus.SUCCESS
            task.output = f"Created {filename}"
            task.cost_usd = 0.01
        except Exception as e:
            task.status = TaskStatus.FAILED
            task.error = str(e)

        task.completed_at = "2026-01-01T00:00:02"

        if on_event:
            await on_event({"type": "result", "task_id": task.id, "status": task.status.value})

        return task


# ============================================================
# Layer 2 测试
# ============================================================

class TestWorktreeRalphIntegration:
    """WorktreePool + RalphLoop 集成。"""

    @pytest.mark.asyncio
    async def test_single_task_full_flow(self, tmp_git_repo):
        """完整流程：submit → acquire worktree → execute → commit → merge → release。"""
        pool = WorktreePool(tmp_git_repo, pool_size=2)
        await pool.init_pool()

        dispatcher = FileCreatingDispatcher(delay=0.01)
        ralph = RalphLoop(dispatcher=dispatcher, pool=pool)
        await ralph.start()

        task = Task(id="intg-001", prompt="create a file")
        await ralph.submit(task)

        # 等待完成
        for _ in range(100):
            await asyncio.sleep(0.05)
            if task.status in (TaskStatus.SUCCESS, TaskStatus.FAILED):
                break

        await ralph.stop()

        # 验证
        assert task.status == TaskStatus.SUCCESS
        # 文件应该已 merge 到 main
        output_file = Path(tmp_git_repo) / f"output_intg-001.py"
        assert output_file.exists(), f"Expected merged file at {output_file}"

        # Worktree 应该被释放
        assert pool.available_count == 2
        assert pool.busy_count == 0

    @pytest.mark.asyncio
    async def test_multiple_tasks_parallel(self, tmp_git_repo):
        """多任务并行执行，都 merge 到 main。"""
        pool = WorktreePool(tmp_git_repo, pool_size=3)
        await pool.init_pool()

        dispatcher = FileCreatingDispatcher(delay=0.02)
        ralph = RalphLoop(dispatcher=dispatcher, pool=pool)
        await ralph.start()

        tasks = [Task(id=f"par-{i:03d}", prompt=f"parallel task {i}") for i in range(3)]
        for t in tasks:
            await ralph.submit(t)

        # 等待全部完成
        for _ in range(200):
            await asyncio.sleep(0.05)
            if all(t.status in (TaskStatus.SUCCESS, TaskStatus.FAILED) for t in tasks):
                break

        await ralph.stop()

        # 所有任务成功
        succeeded = [t for t in tasks if t.status == TaskStatus.SUCCESS]
        assert len(succeeded) >= 2, f"Expected >=2 success, got {len(succeeded)}"

        # 成功的任务文件应该在 main 中
        for t in succeeded:
            f = Path(tmp_git_repo) / f"output_{t.id}.py"
            assert f.exists(), f"Missing merged file: {f}"

        # 所有 worktree 释放
        assert pool.busy_count == 0

    @pytest.mark.asyncio
    async def test_queued_tasks_sequential(self, tmp_git_repo):
        """任务多于 workers 时排队执行。"""
        pool = WorktreePool(tmp_git_repo, pool_size=1)
        await pool.init_pool()

        dispatcher = FileCreatingDispatcher(delay=0.02)
        ralph = RalphLoop(dispatcher=dispatcher, pool=pool)
        await ralph.start()

        tasks = [Task(id=f"seq-{i}", prompt=f"sequential {i}") for i in range(3)]
        for t in tasks:
            await ralph.submit(t)

        for _ in range(300):
            await asyncio.sleep(0.05)
            if all(t.status in (TaskStatus.SUCCESS, TaskStatus.FAILED) for t in tasks):
                break

        await ralph.stop()

        succeeded = [t for t in tasks if t.status == TaskStatus.SUCCESS]
        assert len(succeeded) == 3, f"Expected 3, got {len(succeeded)}: {[(t.id, t.status) for t in tasks]}"

    @pytest.mark.asyncio
    async def test_stats_after_integration(self, tmp_git_repo):
        """执行后统计数据正确。"""
        pool = WorktreePool(tmp_git_repo, pool_size=2)
        await pool.init_pool()

        dispatcher = FileCreatingDispatcher(delay=0.01)
        ralph = RalphLoop(dispatcher=dispatcher, pool=pool)
        await ralph.start()

        tasks = [Task(id=f"st-{i}", prompt=f"stats task {i}") for i in range(2)]
        for t in tasks:
            await ralph.submit(t)

        for _ in range(100):
            await asyncio.sleep(0.05)
            if all(t.status in (TaskStatus.SUCCESS, TaskStatus.FAILED) for t in tasks):
                break

        await ralph.stop()

        stats = ralph.get_stats()
        assert stats["total_tasks"] == 2
        assert stats["by_status"].get("success", 0) == 2
        assert stats["total_cost_usd"] > 0


class TestWebServerAPI:
    """WebServer REST API 测试。"""

    @pytest.mark.asyncio
    async def test_stats_endpoint(self, tmp_git_repo):
        """GET /api/stats 返回正确数据。"""
        pool = WorktreePool(tmp_git_repo, pool_size=2)
        await pool.init_pool()
        dispatcher = FileCreatingDispatcher()
        ralph = RalphLoop(dispatcher=dispatcher, pool=pool)

        server = WebServer(ralph, pool, port=0)  # port=0 让系统分配

        # 直接调用 handler
        from aiohttp.test_utils import make_mocked_request
        request = make_mocked_request("GET", "/api/stats")
        response = await server.handle_stats(request)
        data = json.loads(response.text)

        assert "total_tasks" in data
        assert "by_status" in data
        assert "available_workers" in data

    @pytest.mark.asyncio
    async def test_submit_endpoint(self, tmp_git_repo):
        """POST /api/submit 提交任务。"""
        pool = WorktreePool(tmp_git_repo, pool_size=2)
        await pool.init_pool()
        dispatcher = FileCreatingDispatcher()
        ralph = RalphLoop(dispatcher=dispatcher, pool=pool)

        server = WebServer(ralph, pool, port=0)

        # 模拟 POST request
        from aiohttp.test_utils import make_mocked_request
        request = make_mocked_request("POST", "/api/tasks")

        # 需要 mock request.json()
        async def mock_json():
            return {"prompt": "test task"}
        request.json = mock_json

        response = await server.handle_submit_task(request)
        data = json.loads(response.text)

        assert "id" in data
        assert data["status"] == "pending"

    @pytest.mark.asyncio
    async def test_workers_endpoint(self, tmp_git_repo):
        """GET /api/workers 返回 worker 状态。"""
        pool = WorktreePool(tmp_git_repo, pool_size=3)
        await pool.init_pool()
        dispatcher = FileCreatingDispatcher()
        ralph = RalphLoop(dispatcher=dispatcher, pool=pool)

        server = WebServer(ralph, pool, port=0)

        from aiohttp.test_utils import make_mocked_request
        request = make_mocked_request("GET", "/api/workers")
        response = await server.handle_workers(request)
        data = json.loads(response.text)

        assert isinstance(data, list)
        assert len(data) == 3
